"""init five tables

Revision ID: 205a34a57552
Revises: 
Create Date: 2026-08-19 15:43:27.412883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '205a34a57552'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary_entries',
    sa.Column('id', sa.BINARY(16), nullable=False),
    sa.Column('user_id', sa.BINARY(16), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('content_text', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('mood', sa.String(length=16), nullable=True),
    sa.Column('weather', sa.String(length=16), nullable=True),
    sa.Column('from_schedule_id', sa.BINARY(16), nullable=True),
    sa.Column('client_updated_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_schedule_id', name='uk_from_schedule'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ft_content', 'diary_entries', ['title', 'content_text'], unique=False, mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
    op.create_index('idx_user_date', 'diary_entries', ['user_id', 'entry_date'], unique=False)
    op.create_index('idx_user_updated', 'diary_entries', ['user_id', 'updated_at'], unique=False)
    op.create_table('entry_tags',
    sa.Column('entry_id', sa.BINARY(16), nullable=False),
    sa.Column('tag_id', sa.BINARY(16), nullable=False),
    sa.PrimaryKeyConstraint('entry_id', 'tag_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_tag', 'entry_tags', ['tag_id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.BINARY(16), nullable=False),
    sa.Column('user_id', sa.BINARY(16), nullable=False),
    sa.Column('entry_id', sa.BINARY(16), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('thumb_url', sa.String(length=512), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_entry', 'media', ['entry_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.BINARY(16), nullable=False),
    sa.Column('user_id', sa.BINARY(16), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uk_user_name'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', sa.BINARY(16), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Shanghai', nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_index('idx_entry', table_name='media')
    op.drop_table('media')
    op.drop_index('idx_tag', table_name='entry_tags')
    op.drop_table('entry_tags')
    op.drop_index('idx_user_updated', table_name='diary_entries')
    op.drop_index('idx_user_date', table_name='diary_entries')
    op.drop_index('ft_content', table_name='diary_entries', mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
    op.drop_table('diary_entries')
    # ### end Alembic commands ###
