const { test } = require("node:test")
const assert = require("node:assert/strict")
const { ID, schedule, terminal, entry, intent, setup } = require("./schedules-data-harness.cjs")

test("guest claim backs up first and atomically binds schedules and conversion intentions", async () => {
  let calls = 0
  const h = setup({ "@/capabilities/backupFile": { downloadFullBackup: async () => { calls++; assert.equal(await h.db.meta.get("ownerUserId"), undefined) } } })
  await h.db.schedules.put(terminal({ dirty: 0 }))
  await h.db.entries.put(entry({ dirty: 0 }))
  await h.db.meta.put({ key: "scheduleConversions", value: [{ ...intent(), ownerUserId: "" }] })
  const api = h.load("api/claim.ts")
  const result = await api.claimLocalData("account-a")
  assert.equal(calls, 1); assert.equal(result.schedules, 1)
  assert.equal((await h.db.schedules.get(ID)).dirty, 1)
  assert.equal((await h.db.meta.get("ownerUserId")).value, "account-a")
  assert.equal((await h.db.meta.get("scheduleConversions")).value[0].ownerUserId, "account-a")
  assert.ok((await h.db.meta.get("ownerGeneration")).value)
})
test("same-owner or mismatched-owner checks do not clear or silently reassign local data", async () => {
  let backups = 0
  const h = setup({ "@/capabilities/backupFile": { downloadFullBackup: async () => { backups++ } } })
  await h.db.meta.put({ key: "ownerUserId", value: "account-a" })
  await h.db.schedules.put(schedule())
  const api = h.load("api/claim.ts")
  assert.equal((await api.claimLocalData("account-a")).kind, "sameOwner")
  h.user("account-b")
  const result = await api.claimLocalData("account-b")
  assert.equal(result.kind, "ownerMismatch"); assert.equal(result.localOwner, "account-a")
  assert.equal(backups, 0); assert.equal(h.stores.schedules.rows.size, 1)
})
test("failed backup or mid-backup account change leaves schedules and queue untouched", async () => {
  let mode = "fail"
  const h = setup({ "@/capabilities/backupFile": { downloadFullBackup: async () => {
    if (mode === "fail") throw new Error("download failed")
    h.user("account-b")
  } } })
  await h.db.schedules.put(schedule())
  const api = h.load("api/claim.ts")
  await assert.rejects(api.claimLocalData("account-a"), /download failed/)
  mode = "change"
  await assert.rejects(api.claimLocalData("account-a"), /账号已变化/)
  assert.equal(h.stores.schedules.rows.size, 1)
  assert.equal(await h.db.meta.get("ownerUserId"), undefined)
})
test("successful owner reset clears schedules, draft, queue, P2 metadata and uses a fresh epoch", async () => {
  let backedUp = false
  const h = setup({ "@/capabilities/backupFile": { downloadFullBackup: async () => { backedUp = true } } })
  await h.db.meta.put({ key: "ownerUserId", value: "old-account" })
  await h.db.meta.put({ key: "ownerGeneration", value: "old-epoch" })
  for (const key of ["scheduleConversions", "scheduleDraft", "scheduleLastSyncAt", "pendingPurges", "conflicts"]) await h.db.meta.put({ key, value: ["old"] })
  await h.db.schedules.put(schedule()); await h.db.entries.put(entry())
  await h.load("api/claim.ts").resetLocalForNewOwner("account-a")
  assert.equal(backedUp, true); assert.equal(h.stores.schedules.rows.size, 0)
  assert.equal(h.stores.entries.rows.size, 0)
  assert.equal((await h.db.meta.get("ownerUserId")).value, "account-a")
  assert.notEqual((await h.db.meta.get("ownerGeneration")).value, "old-epoch")
  assert.equal(await h.db.meta.get("scheduleConversions"), undefined)
})
test("clear transaction failure restores every table and all original ownership metadata", async () => {
  const h = setup({ "@/capabilities/backupFile": { downloadFullBackup: async () => {} } })
  await h.db.schedules.put(schedule()); await h.db.entries.put(entry())
  await h.db.meta.put({ key: "ownerUserId", value: "old" })
  await h.db.meta.put({ key: "ownerGeneration", value: "old-epoch" })
  h.failNext("schedules", "clear")
  await assert.rejects(h.load("api/claim.ts").resetLocalForNewOwner("account-a"), /injected/)
  assert.equal(h.stores.entries.rows.size, 1); assert.equal(h.stores.schedules.rows.size, 1)
  assert.equal((await h.db.meta.get("ownerUserId")).value, "old")
  assert.equal((await h.db.meta.get("ownerGeneration")).value, "old-epoch")
})
test("a changed DB owner during download is detected before an empty-store claim", async () => {
  const h = setup({ "@/capabilities/backupFile": { downloadFullBackup: async () => {
    await h.db.meta.put({ key: "ownerUserId", value: "other-tab-owner" })
  } } })
  await assert.rejects(h.load("api/claim.ts").claimLocalData("account-a"), /本地账号/)
  assert.equal((await h.db.meta.get("ownerUserId")).value, "other-tab-owner")
})
test("leases reject login-owner mismatch, logout and same-owner restore epochs", async () => {
  const h = setup(); const api = h.load("api/syncContext.ts")
  await h.db.meta.put({ key: "ownerUserId", value: "account-a" })
  await h.db.meta.put({ key: "ownerGeneration", value: "before" })
  const context = await api.captureSyncContext()
  await api.assertSyncContext(context)
  await h.db.meta.put({ key: "ownerGeneration", value: "restored" })
  await assert.rejects(api.assertSyncContext(context), /恢复批次/)
  h.user("account-b")
  await assert.rejects(api.captureSyncContext(), /归属不一致/)
  h.user("")
  await assert.rejects(api.assertSyncContext(context), /会话已变化/)
})
